name: Windows

on:
  workflow_dispatch:
  # push:
#    branches:
#      - "*"
# Jobs are skipped when ONLY Markdown (*.md) files are changed
#    paths-ignore:
#      - "**.md"
# pull_request:
#    branches:
#      - main
# Jobs are skipped when ONLY Markdown (*.md) files are changed
#    paths-ignore:
#      - "**.md"

env:
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build:
    name: Build
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        # Run several build types
        buildtype: ["Release", "Debug"]
        os: [windows-latest]
      fail-fast: true

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v2
        with:
          path: "**/cpm_modules"
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

      - name: configure
        run: |
          cmake -B ${{github.workspace}}/build -DUSE_FLIP:BOOL=TRUE -DCMAKE_BUILD_TYPE=${{matrix.buildtype}}

      - name: build
        run: cmake --build ${{github.workspace}}/build --parallel --config ${{matrix.buildtype}}

      - name: Checking that darts runs
        working-directory: ${{github.workspace}}
        run: |
          ./build/${{matrix.buildtype}}/darts.exe --help

      - name: Running tests
        working-directory: ${{github.workspace}}
        run: |
          ./build/${{matrix.buildtype}}/darts_tutorial0.exe
          ./build/${{matrix.buildtype}}/darts_tutorial1.exe
          ./build/${{matrix.buildtype}}/point_gen.exe
        # mkdir ./build/${{matrix.buildtype}}/data
        # cd ./build/${{matrix.buildtype}}/
        # ./nanovdb_test.exe

      - name: Comparing generated images against reference
        working-directory: ${{github.workspace}}
        run: |
          mkdir build/${{matrix.buildtype}}/differences
          cd build/${{matrix.buildtype}}/differences
          cp ${{github.workspace}}/scenes/assignment0/*.png .
          cp ${{github.workspace}}/scenes/assignment1/*.png .
          ${{github.workspace}}/build/_deps/flip-build/${{matrix.buildtype}}/flip.exe -et -c diff.csv -t gradient.png -r gradient-ref.png
          ${{github.workspace}}/build/_deps/flip-build/${{matrix.buildtype}}/flip.exe -et -c diff.csv -t cornell_grayscale.png -r cornell_grayscale-ref.png
          ${{github.workspace}}/build/_deps/flip-build/${{matrix.buildtype}}/flip.exe -et -c diff.csv -t 01_xformed_camera_sphere_image.png -r 01_xformed_camera_sphere_image-ref.png
          ${{github.workspace}}/build/_deps/flip-build/${{matrix.buildtype}}/flip.exe -et -c diff.csv -t 01_xformed_camera_ray_image.png -r 01_xformed_camera_ray_image-ref.png
          ${{github.workspace}}/build/_deps/flip-build/${{matrix.buildtype}}/flip.exe -et -c diff.csv -t 01_camera_ray_image.png -r 01_camera_ray_image-ref.png
          ${{github.workspace}}/build/_deps/flip-build/${{matrix.buildtype}}/flip.exe -et -c diff.csv -t 01_manual_ray_image.png -r 01_manual_ray_image-ref.png
          ${{github.workspace}}/build/_deps/flip-build/${{matrix.buildtype}}/flip.exe -et -c diff.csv -t 01_recursive_raytracing.png -r 01_recursive_raytracing-ref.png

      # - name: Check NanoVDB file existence
      #   id: check_files
      #   uses: andstor/file-existence-action@v1
      #   with:
      #     files: "./build/${{matrix.buildtype}}/data/primitives.nvdb"

      # - name: NanoVDB File exists
      #   if: steps.check_files.outputs.files_exists == 'true'
      #   # Only runs if all of the files exists
      #   run: echo All files exists!

      - name: Archive test artifacts
        uses: actions/upload-artifact@v2
        with:
          name: differences-${{ matrix.os }}-${{ matrix.buildtype }}
          path: |
            ${{github.workspace}}/build/${{matrix.buildtype}}/differences/
